[theme]
primaryColor = "#6C55E8"
backgroundColor = "#F6F7FB"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#25263D"
font = "sans serif"

[server]
maxUploadSize = 200

[browser]
gatherUsageStats = false

